Repository SEDEPTI-BC/sad-front-end, pull requests merged in 2020-07, with the labels that each got.

#71 Favicon
  static/favicon.ico
Labels: enhancement, refactor

#70 Agendamento de evento
  .nuxt/index.js
  .nuxt/store.js
  components/NavBar.vue
  components/NavBarAdmin.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/admin/calendario.vue
  pages/admin/equipamentos.vue
  pages/admin/eventos.vue
  pages/agendar.vue
  plugins/vueFilterDateForm.js
  store/schedules.js
Labels: refactor

#75 Validação de formulário
  .nuxt/router.js
  assets/images/talk.png
  components/Loading.vue
  components/LoadingDots.vue
  components/Tick.vue
  pages/agendamento-confirmado.vue
  pages/agendar.vue
Labels: enhancement

#78 Fix time
  pages/agendar.vue
Labels: refactor

#80 Equipments
  pages/admin/equipamentos.vue
  pages/admin/eventos.vue
  store/equipments.js
Labels: enhancement

#83 Disabled days page
  pages/admin/calendario.vue
  pages/admin/eventos.vue
  pages/agendar.vue
Labels: enhancement

#85 Adiciona botão de cancelar no formulário
  pages/admin/calendario.vue
Labels: bug

#86 Edita texto da pagina Sobre
  assets/main.css
  pages/sobre.vue
Labels: enhancement

#87 Sedepti page
  .nuxt/router.js
  components/Footer.vue
  components/FooterAdmin.vue
  pages/sedepti.vue
Labels: enhancement
